### ISSUE TITLE
Target question 1: Are we adequately defining membership?

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/2018_Bylaws#1]
We value the ability to describe our community in as inclusive a sense as possible. In general, we use "members of the community" in reference to a diverse group of people including (but not limited to!) trainers/instructors, workshop organizers, and learners. 

Bylaws, however, need to describe specific groups with rights and responsibilities related to how the organization functions. Section 4 of the bylaws defines Voting Members, and what individuals need to do in order to vote in elections. Are these requirements adequate to define our community of Voting Members?

**Comment by weaverbel** [comment]
I think member organisations definitely need to be mentioned as they are an important part of the community @k8hertweck

**Comment by wrightaprilm** [comment]
I was confused by the section "Application for Voting Membership", because you don't actually apply. But you sort of do - it's your responsibility to make sure that your contact info remains up to date in AMY so you receive ballots. Perhaps this section could be "Responsibilities of Voting Members" and could outline how to remain tracked in our opt-out voting system?

**Comment by npch** [comment]
I think that the definition of individual membership is mostly clear apart from the line:

"Any individual who has  [...] otherwise made a significant contribution to any Lesson Program or The Carpentries organization"

The ambiguity is over who decides that they have made a significant contribution. This could be clarified by giving this right to the Executive Council e.g.:

"Any individual who has  [...] otherwise made a significant contribution in the view of the Executive Council to any Lesson Program or The Carpentries organization"

or by being more specific about what counts as a significant contribution (apart from participating on a committee or being a maintainer or mentor).

**Comment by karinlag** [comment]
I also think that members defined in the Nominations and Elections section was a bit confusing. Maybe use "EC Member" for those who are already on the board? Also, you seem to mean that "Members" (capitalized) are EC members, while "members" are individual members? If so, that could be confusing.

**Comment by k8hertweck** [comment]
Thanks for your feedback, folks. Your comments have been addressed in our [second draft](https://github.com/carpentries/2018_Bylaws/blob/master/bylaws_v2.md).

@wrightaprilm Thanks for that suggestion; the subheading has been updated!

@npch The responsibility for determining "significant contribution" has been clarified, thanks.

@karinlag Language throughout the bylaws has been standardized and updated, many thanks!
