### ISSUE TITLE
Eligibility, Rights, and Termination of Organizational Members too vague

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/2018_Bylaws#4]
This was frighteningly vague to me. Made me think that if I were signing up I might have wildly different terms of membership than some other org. Maybe state some basic/common bylaws here with the caveat that signed agreements may supersede some/all of the general bylaws?

**Comment by npch** [comment]
I agree with @JasonJWilliamsNY - in particular I would have liked to have seen the "voting rights" of organisational members enshrined in the bylaws, even if other rights are kept in the membership agreements.

Will membership agreements be published / available for inspection by the community?

**Comment by k8hertweck** [comment]
Thanks for this feedback. 

We've added language pulled from the [website's description of membership](https://carpentries.org/membership/), which represents a layperson's (nonlegal) explanation of the major parts of the membership agreements, which can be found in #15 

@npch We've decided not to include votes for organizational members, in part because it logistically amounts to two votes for many individuals (as often the points of contact are Voting Members themselves), and because this hasn't appeared to provide added value to signing a membership agreement. I suspect if this will change as the organization continues to grow and mature, though, and would be worth revisiting following development of the Membership Council.
