### ISSUE TITLE
Combine voting membership rules 1, 2, and 3?

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/2018_Bylaws#5]
I feel like rules 1, 2, and 3 can be combined into one rule...

Voting rights are granted every instructor or trainer upon their certification for one year. Membership is automatically renewed and extended on the anniversary of their certification provided they teach at least one Carpentries workshop within that year. 

(Example: Instructor certified on July 1st, 2018 will have voting rights until June 30th, 2019. Provided they have taught at least one workshop on on before their membership expiration date their membership will be aromatically renewed for July 1, 2019 - June 20, 2020.)

**Comment by npch** [comment]
The only thing I don't like about this is the requirement to teach one workshop each year rather than two every two years - there are a variety of good reasons that someone may not be able to teach within a year timeframe (sabbatical, parental leave, work pressure) but it feels wrong that they drop off after just one year.

**Comment by k8hertweck** [comment]
We've clarified the timing of workshop tracking (#12 ); it's far easier for the staff to manage this by specific calendar dates for everyone (rather than tracked by when instructor training was completed). We've left the requirement at a workshop each year to maintain Voting Membership; if someone teaches less but are a member of committee and/or continue to stay involved in the community otherwise, they are welcome to apply for Voting membership.
